hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: base-gateway
zuul:
  routes:
    service-notification:
      path: /notification/**
      serviceId: service-notification
#      stripPrefix: false
#    api-a:
#      path: /api-a/**
#      serviceId: service-notification
#      stripPrefix: false
#    api-b:
#      path: /api-b/**
#      serviceId: service-notification